# Generated by Django 3.2.3 on 2022-12-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
