# Generated by Django 3.2.3 on 2022-12-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
