# Generated by Django 3.2.3 on 2022-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upvotes',
            field=models.TextField(default=''),
        ),
    ]
