# Generated by Django 3.2.3 on 2022-12-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0006_user_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upvotes',
        ),
    ]
