# Generated by Django 3.2.3 on 2022-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
