# Generated by Django 3.2.3 on 2022-11-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_way_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='check',
        ),
    ]
