# Generated by Django 3.2.3 on 2022-12-13 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_remove_way_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='downvotes',
            field=models.ManyToManyField(related_name='negative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='way',
            name='upvotes',
            field=models.ManyToManyField(related_name='positive', to=settings.AUTH_USER_MODEL),
        ),
    ]
