# Generated by Django 3.2.3 on 2022-12-15 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_auto_20221213_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='downvotes',
            field=models.ManyToManyField(default=[], related_name='negative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='way',
            name='upvotes',
            field=models.ManyToManyField(default=[], related_name='positive', to=settings.AUTH_USER_MODEL),
        ),
    ]
