# Generated by Django 3.2.3 on 2022-12-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20221215_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='upvotes',
        ),
    ]
