# Generated by Django 3.2.3 on 2022-12-18 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0006_remove_way_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='upvotes',
            field=models.ManyToManyField(default='', related_name='positive', to=settings.AUTH_USER_MODEL),
        ),
    ]
