# Generated by Django 3.2.3 on 2022-12-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_way_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='way',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
