# Generated by Django 3.2.3 on 2022-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20221218_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='upvotes',
            field=models.TextField(default=''),
        ),
    ]
