# Generated by Django 3.2.3 on 2022-12-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20221218_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='downvotes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='upvotes',
            field=models.TextField(default='', null=True),
        ),
    ]
