# Generated by Django 3.2.3 on 2022-12-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='way',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.way'),
        ),
    ]
