# Generated by Django 3.2.3 on 2022-12-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_comment_way'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
